export {default as Activities} from './Activities'
export {default as Routines} from './Routines'
export {default as Profile} from './Profile'
export {default as MyRoutines} from './MyRoutines'
export {default as AccountForm} from './AccountForm'